# Generated by Django 4.2.16 on 2025-06-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('about', '0002_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(help_text="What's your cake called?", max_length=200)),
                ('description', models.TextField(help_text='Tell us about your cake!')),
                ('image', models.ImageField(help_text='Upload a photo of your cake', upload_to='cake_submissions/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes (not visible to user)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cake_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cake Submission',
                'verbose_name_plural': 'Cake Submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
