# Generated by Django 4.2.16 on 2025-06-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_cakesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
