# Generated by Django 4.2.16 on 2025-06-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('cake_flavor', models.CharField(choices=[('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('tiramisu', 'Tiramisu'), ('oreo', 'Oreo'), ('lime', 'Lime'), ('dulce_de_leche', 'Dulce de Leche'), ('custom', 'Custom Flavor')], max_length=20)),
                ('custom_flavor_description', models.TextField(blank=True, help_text='Describe your custom flavor if selected')),
                ('cake_size', models.CharField(help_text='e.g., 6-inch, 8-inch, 10-inch, etc.', max_length=50)),
                ('servings', models.PositiveIntegerField(help_text='Number of servings needed')),
                ('design_description', models.TextField(help_text='Describe your desired cake design')),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or dietary requirements')),
                ('event_date', models.DateField(help_text='When do you need the cake?')),
                ('event_type', models.CharField(help_text='e.g., Birthday, Wedding, Anniversary, etc.', max_length=100)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('ready', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to customer)')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
    ]
