# Generated by Django 4.2.16 on 2025-06-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='servings',
        ),
        migrations.AlterField(
            model_name='order',
            name='cake_size',
            field=models.CharField(choices=[('15', '15 cm (6 inch)'), ('20', '20 cm (8 inch)'), ('25', '25 cm (10 inch)'), ('30', '30 cm (12 inch)')], help_text='Cake diameter in centimeters', max_length=2),
        ),
    ]
