# Generated by Django 4.2.16 on 2025-06-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_remove_order_servings_alter_order_cake_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated price in SEK', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final price in SEK', max_digits=8, null=True),
        ),
    ]
